import { spawnSync } from 'node:child_process';
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { afterEach, describe, expect, it } from 'vitest';

const RELEASE_NOTES_SCRIPT = fileURLToPath(
  new URL('../../scripts/release-notes.mjs', import.meta.url),
);
const temporaryDirectories: string[] = [];

function extract(tag: string, changelog: string) {
  const directory = mkdtempSync(join(tmpdir(), 'aitrack-release-notes-'));
  temporaryDirectories.push(directory);
  const changelogPath = join(directory, 'CHANGELOG.md');
  writeFileSync(changelogPath, changelog, 'utf8');
  return spawnSync(process.execPath, [RELEASE_NOTES_SCRIPT, tag, changelogPath], {
    encoding: 'utf8',
  });
}

afterEach(() => {
  for (const directory of temporaryDirectories.splice(0)) {
    rmSync(directory, { recursive: true, force: true });
  }
});

describe('GitHub release notes', () => {
  it('extracts only the requested changelog release section', () => {
    const result = extract(
      'v2.0.0',
      `# Changelog

## [v2.0.0] - 2026-07-24

### Features

- Add release publishing

## [v1.9.0] - 2026-07-01

### Features

- Older feature
`,
    );

    expect(result.status).toBe(0);
    expect(result.stderr).toBe('');
    expect(result.stdout).toBe('### Features\n\n- Add release publishing\n');
    expect(result.stdout).not.toContain('Older feature');
  });

  it('matches a compare-link heading emitted by git-cliff', () => {
    const result = extract(
      'v2.0.0',
      `# Changelog

## [v2.0.0](https://example.com/compare/v1.9.0..v2.0.0) - 2026-07-24

### Features

- Add release publishing

## [v1.9.0](https://example.com/compare/v1.8.0..v1.9.0) - 2026-07-01

- Older feature
`,
    );

    expect(result.status).toBe(0);
    expect(result.stderr).toBe('');
    expect(result.stdout).toBe('### Features\n\n- Add release publishing\n');
    expect(result.stdout).not.toContain('Older feature');
  });

  it('excludes git-cliff trailers below the final section', () => {
    const result = extract(
      'v1.0.0',
      `# Changelog

## [v1.0.0] - 2026-01-01

### Features

- First release

<!-- generated by git-cliff -->
[v1.0.0]: https://example.com/releases/tag/v1.0.0
`,
    );

    expect(result.status).toBe(0);
    expect(result.stdout).toBe('### Features\n\n- First release\n');
    expect(result.stdout).not.toContain('git-cliff');
    expect(result.stdout).not.toContain('https://example.com');
  });

  it('supports prerelease tags and the final changelog section', () => {
    const result = extract(
      'v2.0.0-beta.1',
      `# Changelog

## [v2.0.0-beta.1]

### Bug Fixes

- Fix the preview
`,
    );

    expect(result.status).toBe(0);
    expect(result.stdout).toContain('Fix the preview');
  });

  it('fails instead of publishing notes for the wrong tag', () => {
    const result = extract('v3.0.0', '# Changelog\n\n## [v2.0.0] - 2026-07-24\n\n- Done\n');

    expect(result.status).toBe(1);
    expect(result.stderr).toContain('Could not find a v3.0.0 section');
    expect(result.stdout).toBe('');
  });

  it('rejects an empty release section', () => {
    const result = extract(
      'v2.0.0',
      '# Changelog\n\n## [v2.0.0] - 2026-07-24\n\n## [v1.0.0] - 2026-01-01\n\n- Old\n',
    );

    expect(result.status).toBe(1);
    expect(result.stderr).toContain('v2.0.0 changelog section is empty');
  });
});
